In [5]:
import pandas as pd
import numpy as np
import warnings
import seaborn as sns
warnings.filterwarnings('ignore')

In [3]:
df = sns.load_dataset('iris')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [7]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [9]:
from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()
lb.fit_transform(df['species'])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [18]:
#df['embarked'].unique()

In [20]:
df=sns.load_dataset('titanic')
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [24]:
df['embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [26]:
df['embarked']

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: embarked, Length: 891, dtype: object

In [32]:
from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()
df['embarked'] = lb.fit_transform(df['embarked'])


In [35]:
df['embarked'].unique()

array([2, 0, 1, 3], dtype=int64)

In [37]:
df['sex'].unique()

array(['male', 'female'], dtype=object)

In [39]:
df['sex'] = lb.fit_transform(df['sex'])

In [41]:
df['sex'].unique()

array([1, 0])

In [43]:
df['class'].unique()

['Third', 'First', 'Second']
Categories (3, object): ['First', 'Second', 'Third']

In [47]:
df['age'].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [49]:
df['age'] = lb.fit_transform(df['age'])

In [51]:
df['age'].unique()

array([28, 51, 34, 47, 88, 69,  6, 35, 18,  8, 74, 25, 52, 70, 41, 45, 20,
       36, 12, 24, 53, 82, 56, 27, 23,  7, 11, 64, 38, 81, 37,  9, 15, 59,
       22, 42, 21, 33,  3, 39, 44, 29, 31, 61, 75, 85, 50, 62, 19, 84, 43,
       16, 13, 49, 66, 71, 54, 58,  5, 77, 72, 65, 48, 60, 26, 78, 55, 67,
       79, 30,  4, 57, 76, 14, 80, 17, 63,  2, 68, 73, 87, 83, 32, 10,  1,
       40,  0, 46, 86], dtype=int64)

In [53]:
df['survived'].unique()

array([0, 1], dtype=int64)

In [55]:
df['survived'] = lb.fit_transform(df['survived'])

In [57]:
df['survived'].unique()

array([0, 1], dtype=int64)

In [59]:
df['who'].unique()

array(['man', 'woman', 'child'], dtype=object)

In [61]:
df['who'] = lb.fit_transform(df['who'])

In [63]:
df['who'].unique()

array([1, 2, 0])

In [65]:
df['fare'].unique()

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
        31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,  18.    ,
         7.225 ,  26.    ,   8.0292,  35.5   ,  31.3875, 263.    ,
         7.8792,   7.8958,  27.7208, 146.5208,   7.75  ,  10.5   ,
        82.1708,  52.    ,   7.2292,  11.2417,   9.475 ,  21.    ,
        41.5792,  15.5   ,  21.6792,  17.8   ,  39.6875,   7.8   ,
        76.7292,  61.9792,  27.75  ,  46.9   ,  80.    ,  83.475 ,
        27.9   ,  15.2458,   8.1583,   8.6625,  73.5   ,  14.4542,
        56.4958,   7.65  ,  29.    ,  12.475 ,   9.    ,   9.5   ,
         7.7875,  47.1   ,  15.85  ,  34.375 ,  61.175 ,  20.575 ,
        34.6542,  63.3583,  23.    ,  77.2875,   8.6542,   7.775 ,
        24.15  ,   9.825 ,  14.4583, 247.5208,   7.1417,  22.3583,
         6.975 ,   7.05  ,  14.5   ,  15.0458,  26.2833,   9.2167,
        79.2   ,   6.75  ,  11.5   ,  36.75  ,   7.7958,  12.5

In [67]:
df['fare'] = lb.fit_transform(df['fare'])

In [69]:
df['fare'].unique()

array([ 18, 207,  41, 189,  43,  51, 186, 124,  74, 154, 110, 143, 158,
        36, 108, 151,  85, 113,  16, 138,  42, 168, 159, 246,  38,  40,
       145, 236,  30,  72, 220, 187,  17,  75,  62, 123, 177, 102, 125,
       112, 175,  34, 211, 200, 146, 179, 218, 222, 147, 101,  46,  54,
       208,  94, 193,  24, 150,  81,  58,  64,  32, 180, 106, 165, 198,
       122, 166, 201, 129, 212,  53,  31, 133,  66,  95, 244,  15, 127,
        10,  12,  96,  98, 140,  59, 216,   7,  76, 169,  33,  82, 203,
        19, 199,  27, 205, 109, 105, 121, 190, 136, 163, 156, 134, 149,
         0,  99, 172, 126, 183,  49,   6,  71, 115, 157, 231, 144, 210,
       225,  61,  87,  22, 139,  78,  14, 188, 119, 223, 247, 217, 238,
       235, 117, 152, 213, 120, 215, 226,  84,  57, 237, 155, 130,  80,
       230, 229, 132, 194, 221, 245,  91, 239, 234,   3, 196, 148, 233,
       107,  60, 167, 209, 204, 191, 241,   1, 243, 104,  26,  77, 232,
        83, 114,   8, 161,  37,  93, 192,  44, 219, 116, 118, 22

In [71]:
df['alive'].unique()

array(['no', 'yes'], dtype=object)

In [73]:
df['alive'] = lb.fit_transform(df['alive'])

In [75]:
df['alive'].unique()

array([0, 1])

In [77]:
print('Before ',df['who'].unique())
df['who'] = lb.fit_transform(df['who'])
print('After ',df['who'].unique())

Before  [1 2 0]
After  [1 2 0]


In [79]:
print('Before ',df['age'].unique())
df['age'] = lb.fit_transform(df['age'])
print('After ',df['age'].unique())

Before  [28 51 34 47 88 69  6 35 18  8 74 25 52 70 41 45 20 36 12 24 53 82 56 27
 23  7 11 64 38 81 37  9 15 59 22 42 21 33  3 39 44 29 31 61 75 85 50 62
 19 84 43 16 13 49 66 71 54 58  5 77 72 65 48 60 26 78 55 67 79 30  4 57
 76 14 80 17 63  2 68 73 87 83 32 10  1 40  0 46 86]
After  [28 51 34 47 88 69  6 35 18  8 74 25 52 70 41 45 20 36 12 24 53 82 56 27
 23  7 11 64 38 81 37  9 15 59 22 42 21 33  3 39 44 29 31 61 75 85 50 62
 19 84 43 16 13 49 66 71 54 58  5 77 72 65 48 60 26 78 55 67 79 30  4 57
 76 14 80 17 63  2 68 73 87 83 32 10  1 40  0 46 86]


In [81]:
print('Before ',df['sex'].unique())
df['sex'] = lb.fit_transform(df['sex'])
print('After ',df['sex'].unique())

Before  [1 0]
After  [1 0]


In [83]:
print('Before ',df['fare'].unique())
df['fare'] = lb.fit_transform(df['fare'])
print('After ',df['fare'].unique())

Before  [ 18 207  41 189  43  51 186 124  74 154 110 143 158  36 108 151  85 113
  16 138  42 168 159 246  38  40 145 236  30  72 220 187  17  75  62 123
 177 102 125 112 175  34 211 200 146 179 218 222 147 101  46  54 208  94
 193  24 150  81  58  64  32 180 106 165 198 122 166 201 129 212  53  31
 133  66  95 244  15 127  10  12  96  98 140  59 216   7  76 169  33  82
 203  19 199  27 205 109 105 121 190 136 163 156 134 149   0  99 172 126
 183  49   6  71 115 157 231 144 210 225  61  87  22 139  78  14 188 119
 223 247 217 238 235 117 152 213 120 215 226  84  57 237 155 130  80 230
 229 132 194 221 245  91 239 234   3 196 148 233 107  60 167 209 204 191
 241   1 243 104  26  77 232  83 114   8 161  37  93 192  44 219 116 118
 224 171  25  88  67  11  21  79  65 182 214 100  23 128 141 197  20 164
 227 242 228 181 206  90  35 174 111 185 142 153 176  56  97 162 178 103
 202 160  13  50 135  68  45  70 240 195  86  29  63  28  48 131 137  55
  52  39 170   5   9  47   4 173  92  89 18